### ISSUE TITLE
如果返回值是用括号包起来的 无法进行自动注释

### ISSUE THREAD

**Issue by iiiusky** [kiexu/func-comment#1]
如果返回值是用括号包起来的 无法进行自动注释
比如这样 
`func xxx(ccc string , ddd string) (err error)`

或这样 `func xxx(ccc string , ddd string) (xxx string,err error)`

都是无法进行自动注释的~

**Comment by kiexu** [comment]
你好：
谢谢你的建议，已经修复了这个问题。
但新版返回值格式发生了变化，如果存在返回值，现在统一打印"return:"，不打印返回值变量名称了。
